### ISSUE TITLE
BUG:IndexError: list index out of range

### ISSUE THREAD

**Issue by Ompsda** [QIMP-Team/MOOSE#41]
I am running MOOSE in a patient folder with two subfolders for CT and PET under DCIOM format. However, I am getting this error  message:

   moose_ct_atlas = ie.segment_ct(ct_file[0], out_dir)
  File "/export/moose/moose-0.1.0/src/inferenceEngine.py", line 78, in segment_ct
    out_label = fop.get_files(out_dir, pathlib.Path(nifti_img).stem + '*')[0]
IndexError: list index out of range

Any suggestion, please?

Thanks,

**Comment by LalithShiyam** [comment]
Hello, does your PET image have the brain in the field-of-view? If no, please delete the PET dicom folder and everything should run fine.

**Comment by Ompsda** [comment]
Yes, it contains the brain in the FOV.

**Comment by LalithShiyam** [comment]
Ok, interesting! Would you be kind enough to share the folder structure (along with the generated files), I can have have a look. If the files are anonymous you can also send them to my mail ID: Lalith.shiyamsundar@meduniwien.ac.at

would make the debugging process much easier :)

**Comment by Ompsda** [comment]
Thank you so much! I just sent you the screenshots via email. The DICOM files are not anonymous. If it doesn't help, let me know, and I will find anonymous DICOM files.

Again, thank you so much.

**Comment by Ompsda** [comment]
I have anonymized the patient data. I can send it to you. I am not familiar with github, can I send it through BOX?'
Thanks,
Mahdjoub

**Comment by LalithShiyam** [comment]
Sure share it via box. I saw your screenshots. It seems like the models are not being run on your dataset. Can be a path issue. But let me confirm once I have anonymous datasets from you :)! 
Cheers!

**Comment by Ompsda** [comment]
I have shared the DICOM data with you. 
Let me know if you need anything.

Again, your help is very appreciated. 

Thank you!

**Comment by LalithShiyam** [comment]
Excellent! I got your mail. I am traveling now. I will work on it first thing tomorrow :)!

**Comment by Ompsda** [comment]
Thank so much!

**Comment by LalithShiyam** [comment]
Hi @Ompsda, 
I ran your dataset, the results are sent to you via mail. 
I am writing the response here, so that we avoid duplicates in the future. 
Couple of things that you should check.
- When I first ran it, MOOSE recognised the AC map as ‘MR’. Because I assume you pushed the CT maps to MR-AC headers. Since MOOSE organises things based on the DICOM tags, I changed the modality tag of the DICOM header to CT.
- Then I ran the stuff, MOOSE worked. However, when I checked your screenshot of the MOOSE print logs, It seems that the inference of the CT abdominal organs was not done. Would you be kind enough to check the environment variables by using the following commands in your command line terminal
	'echo $RESULTS_FOLDER’
This should display the path where the nnUNet based models are stored. If you don’t see anything, you should source your bashrc file. If it still doesn’t work, I would ask you to check your .bashrc file for the nnUNet based environment variables entry. You need to ideally have three entries in the file.
Please let me know how it goes.
Will be glad to help.

**Comment by LalithShiyam** [comment]
@Ompsda : any luck with getting moose to run? Also if it didn't work, please use the [latest version of moose](https://github.com/QIMP-Team/MOOSE/releases/tag/moose-v0.1.4)!

**Comment by Ompsda** [comment]
Hi,
I think the issue is that the software was not developed to work on CHPC. Our CHPC admin stated he cannot install it following your instructions on Github. Also, the best workstation we have has 64 G RAM, which is lower than what MOOSE requires.

Thanks,

**Comment by LalithShiyam** [comment]
Hi there,
I am sorry that the admin was not positive to the installation of moose. 
If it helps, I am available to discuss with your IT admin to see if moose can be installed in your cluster. Ideally the docker image should work without any issues. 
I am happy to help if your admin is interested in coordinating this effort.
Cheers,
Lalith

**Comment by Ompsda** [comment]
Hi Latih,
Thank you for being responsive. I wanted to give MOOSE a try, however, it is not a priority for us now. I will let you know in case we want to use it in the future.
Thank you,
