### ISSUE TITLE
BUG: WSL does not have unzip installed and moose falls silently due to wrong installation. 

### ISSUE THREAD

**Issue by paula-m** [QIMP-Team/MOOSE#44]
MOOSE fails with index error when trying to run on WSL, due to wrong installation. There is no moose-files folder created when the algorithm is installed. 

Install through WSL as described in github. 

Moose-files folder should be created when installed, and moose should run as required. 

Screenshots of the errors:
![image](https://user-images.githubusercontent.com/61393624/197759907-14917a24-3564-4a8e-8d9d-fca4e32fcc59.png)
![image](https://user-images.githubusercontent.com/61393624/197759836-ab5185a5-ea92-4459-937a-fd5844aaae24.png)

Windows 11 22H2

**Comment by LalithShiyam** [comment]
Hi @paula-m, thanks for opening the issue. 
The reason why `moose` fails is due to the fact that the models are not unzipped before they are deleted. The reason is WSL doesn't have `unzip` utility preinstalled unlike native ubuntu.
The solution for this bug would be to install `unzip` before `moose` installation. Once `unzip` is installed, everything should ideally work.

I am closing this for now, keep me posted, if something else crashes or burns!
