### ISSUE TITLE
Can you help mi solve this error.Thanks,I use window10 system.

### ISSUE THREAD

**Issue by shifuxiao** [QIMP-Team/MOOSE#76]
(moose-env) E:\data>moosez -d ./input -m clin_ct_organs_v2

     __  _______  ____  ________  ___   ___ 
    /  |/  / __ \/ __ \/ __/ __/ |_  | / _ \
   / /|_/ / /_/ / /_/ /\ \/ _/  / __/_/ // /
  /_/  /_/\____/\____/___/___/ /____(_)___/
 A part of the ENHANCE community. Join us at www.enhance.pet to build the future of PET imaging together.

 � CITATION:

 Shiyam Sundar LK, Yu J, Muzik O, et al. Fully-automated, semantic segmentation of whole-body 18F-FDG PET/CT images based on data-centric artificial intelligence. J Nucl Med. June 2022.
 Copyright 2022, Quantitative Imaging and Medical Physics Team, Medical University of Vienna

 � NOTE:

 Imaging: Clinical | Modality: CT | Tissue of interest: Organs | nnUNet version: v2
 Required modalities: ['CT'] |  No. of modalities: 1 | Required prefix for non-DICOM files: ['CT_']
 Warning: Subjects which don't have the required modalities [check file prefix] will be skipped. 
CUDA not available on this device. Predictions will be run on CPU.

 � MODEL DOWNLOAD:

 A local instance of Dataset123_Organs has been detected. 

 � STANDARDIZING INPUT DATA TO NIFTI:

 Processing subjects... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--
 Standardization complete.
 Number of moose compliant subjects: 0 out of 0 

 � PREDICT:

Traceback (most recent call last):
  File "D:\anaconda3\envs\moose-env\lib\runpy.py", line 197, in _run_module_as_main
\ Initiating    return _run_code(code, main_globals, None,
  File "D:\anaconda3\envs\moose-env\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\anaconda3\envs\moose-env\Scripts\moosez.exe\__main__.py", line 7, in <module>
  File "C:\Users\DELL\AppData\Roaming\Python\Python39\site-packages\moosez\moosez.py", line 199, in main
    time_per_dataset = total_elapsed_time / len(moose_compliant_subjects)
ZeroDivisionError: float division by zero

**Comment by LalithShiyam** [comment]
Hi @shifuxiao, 

Would you be kind enough to let me know the moosez version you are using. My guess is that you are using 2.2.8? Any particular reason why? If you are really interested in the organs, I would suggest to use the latest version of moosez. The organ model is much more robust since the training data was larger.

Please upgrade using `pip install --upgrade moosez`!

Also the error you are seeing is basically because there are no moose compatible directory structure. Kindly have a look at the [readme](https://github.com/qimp-team/moose#required-directory-structure-) section!

**Comment by LalithShiyam** [comment]
Hi @shifuxiao, is this solved? Kindly update!

**Comment by LalithShiyam** [comment]
@shifuxiao I am closing this, assuming this issue has been solved.
