### ISSUE TITLE
MRI model is for rats but not for humans.

### ISSUE THREAD

**Issue by LinLiMax1** [QIMP-Team/MOOSE#94]
**Describe the bug**
I tried the CT models and it worked very well, but the MRI model preclin_mr_all didn't generate good results.
Update: I missed the information in the document. The MRI model is for rats but I used it in humans. Thank you for your clarification!

**Screenshots**
<img width="1087" alt="image" src="https://github.com/QIMP-Team/MOOSE/assets/99052349/d2f652ce-f07e-4b83-ba71-3cfba770308a">

**Comment by LalithShiyam** [comment]
Hi @LinLiMax1 

I saw the screenshot and it looks like a clinical-MR of the heart. I can't view the actual NIFTI image as I am on vacation.  
We don't have models for clinical MRs. The model that you used is for "preclinical MR", that's why it starts with "preclin_". 

Refer this: 

`Update AVAILABLE_MODELS List ✏️

Include your model's unique identifier to the AVAILABLE_MODELS list in the resources.py file. The model name should follow a specific syntax: 'clin' or 'preclin' (indicating Clinical or Preclinical), modality tag (like 'ct', 'pt', 'mr'), and then the tissue of interest.`

Kindly confirm if your data is clinical or preclinical, so that we can help you accordingly. 

Cheers,
Lalith

**Comment by LinLiMax1** [comment]
Hi Lalith,

Thank you so much for your prompt response! For the difference between pre-clinical MRI and clinical MRI, did you mean the difference between MRI taken by healthy people and in-hospital patients? If this is the case, it seems likely that a model trained on pre-clinical data might not perform as accurately on clinical datasets. The issue I'm facing is that the model doesn't produce segmentations like an organ or tissue. I'm concerned this might be due to an issue with the model weights or perhaps an error in how I'm generating the images.

Could you assist in resolving this when you have time after your vacation? Alternatively, could you provide a pre-clinical MRI image for me to test?

Additionally, I'd appreciate more information about the dataset used to train this preclinical MRI model. Thank you so much again for replying to this issue quickly during your vacation!

Best,

Lin Li

**Comment by LalithShiyam** [comment]
Hi @LinLiMax1,
Preclinical means it is a model for segmenting organs from rats/mice. Clinical = humans.

**Comment by LinLiMax1** [comment]
Thank makes sense now.....Thank you so much......
